version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: gomod
    directory: /services/worker
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /services/python
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
